#!/bin/sh
ldd /usr/bin/dmenu | grep -q libXft && \
    FONT="Consolas-10" || \
    FONT="-*-terminus-medium-*-*-*-18-*-*-*-*-*-iso10646-*"

dmenu_run -fn $FONT -nb '#000000' -nf '#FFFFFF' -sb '#0066ff'
