#!/bin/sh

NB="#122212"
NF="#DEDEDE"
SB="#445444"
SF="#EFEFEF"
MISC="-i -l 10"
ldd /usr/bin/dmenu | grep -q libXft && \
    FONT="Consolas-9" || \
    FONT="-*-terminus-medium-*-*-*-18-*-*-*-*-*-iso10646-*"

DMENU="dmenu -fn $FONT -nb $NB -nf $NF -sb $SB -sf $SF $MISC"
#DMENU="xwinmosaic -rp -S -W 600 -H 30 -t -i 24"
isfn ()
{
    type $1 | grep -q 'shell function'
}

# X windows
xwin_ls ()
{
    wmctrl -l | awk '{print substr($0, index($0,$4))}'
}

xwinfmt_ls ()
{
#    wmctrl -xl | \
#        awk '{split($3, class, "."); print ",," tolower(class[2]) "," substr($0, index($0,$5)) ","}'
# ignore emacs
    wmctrl -xl | \
        awk '{if ($3 != "emacs.Emacs") { split($3, class, "."); print ",," tolower(class[2]) "," substr($0, index($0,$5)) ","}}'
}

xwin_sw ()
{
    wmctrl -F -a "$1"
}

xwinfmt_sw ()
{
    wmctrl -F -a "$1"
}

# X desktops
xdesk_ls ()
{
    wmctrl -d | awk '{print substr($0, index($0,$9))}'
}

xdesk_sw ()
{
    wrkid=`wmctrl -d | awk "/$1/"'{print $1}'`
    test $wrkid && wmctrl -s $wrkid
}

# emacs buffers
ebuf_ls ()
{
    emacsclient --eval \
        '(mapconcat (quote (lambda (s) (format "%s" s)))
	    (remove-if (quote (lambda (name) (string= (substring name 0 1) " ")))
		       (mapcar (quote buffer-name) (buffer-list)))
		       "\n")' \
                           | xargs echo -e
}

ebuf_sw ()
{
    ebuf_ls | grep -x -F -q -e "$1" && \
        emacsclient -c --eval "(switch-to-buffer \"$1\")"
}

# from emacs fancy
emacs_ls ()
{
    emacsclient --eval '(xwm-list-buffers)' | xargs echo -e
}

emacs_sw ()
{
    emacs_ls |awk -F',' '{ print $4 }'| grep -x -F -q -e "$1" && \
        emacsclient --eval "(switch-to-buffer \"$1\")"
}


kvm_ls ()
{
    ps ax | grep kvm | sed -n 's/^.*-name \([^[[:blank:]]*\) .*$/\1/p'
}

kvm_sw ()
{
     dp=`ps ax | grep "kvm -name $1" | sed -n 's/^.*-vnc \([^[[:blank:]]*\) .*$/\1/p'`
     xtightvncviewer $dp
}
args="$@"

# collect items
items=""
for a in $args; do
    isfn ${a}_ls && items="$items\n"`${a}_ls`
done

# select
sel=`echo "$items" | grep -v ^$ | sort -u | $DMENU`
test -z "$sel" && exit 0 # 1?

# try to switch
for a in $args; do
    isfn ${a}_sw && `${a}_sw "$sel"` 2>/dev/null && exit 0
done

exit 1
